### ISSUE TITLE
How can others access

### ISSUE THREAD

**Issue by Ykong1337** [prabirshrestha/rblog#153]
Under the same LAN, other people cannot access the blog

**Comment by prabirshrestha** [comment]
You need to set the HOST env variable.

https://github.com/prabirshrestha/rblog/blob/0be09eebe78231758e19d0d4aab01c84bf9a71f2/src/server.rs#L18

currently it defaults to 127.0.0.1 for security reasons. You can set the interface up you prefer or 0.0.0.0 if you want to listen on all.
